# Generated by Django 4.0.6 on 2022-08-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
