# Generated by Django 4.0.6 on 2022-08-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0003_delete_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('fecha_entrega', models.DateField()),
                ('entregado', models.DateField()),
            ],
        ),
    ]
