# Generated by Django 4.0.6 on 2022-08-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0004_entregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('apellido', models.CharField(max_length=38)),
                ('deporte', models.CharField(max_length=38)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('apellido', models.CharField(max_length=38)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=38)),
                ('apellido', models.CharField(max_length=38)),
                ('deporte', models.CharField(max_length=38)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
